name: perle
description: A wallpaper app


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  loading_animation_widget:
  flutter_slider_drawer: ^2.1.2
  screen_loader: ^4.0.1
  modal_bottom_sheet: ^2.1.2
  get:
  flare_flutter: ^3.0.2
  image_downloader: ^0.31.0
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.4
  fluentui_system_icons: ^1.1.189




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
  
